name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # change to your version

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run static analysis
     # - name: Run Flutter Analyzer
      #  run: flutter analyze

      # Run tests
      #- name: Run Tests
      #  run: flutter test --no-pub

      # Build APK (Only runs if a tag is pushed)
      - name: Build APK
        if: startsWith(github.ref, 'refs/tags/')
        run: flutter build apk --release

      # Upload the APK as CI artifact (Only runs if a tag is pushed)
      - name: Upload APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
